services:
  master:
    image: apache/spark:3.3.3
    container_name: master
    hostname: master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - 8080:8080
      - 7077:7077
      - 15002:15002
    volumes:
      - ./spark/conf:/opt/spark/conf
      - ./work/data:/data

  slave1:
    image: apache/spark:3.3.3
    container_name: slave1
    hostname: slave1
    environment:
      - SPARK_MASTER_HOST=master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    ports:
      - 8081:8081
    volumes:
      - ./spark/conf:/opt/spark/conf
      - ./spark/work:/opt/spark/work
      - ./work/data:/data

  slave2:
    image: apache/spark:3.3.3
    container_name: slave2
    hostname: slave1
    environment:
      - SPARK_MASTER_HOST=master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    ports:
      - 8082:8081
    volumes:
      - ./spark/conf:/opt/spark/conf
      - ./spark/work:/opt/spark/work
      - ./work/data:/data

  slave3:
    image: apache/spark:3.3.3
    container_name: slave3
    hostname: slave1
    environment:
      - SPARK_MASTER_HOST=master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    ports:
      - 8083:8081
    volumes:
      - ./spark/conf:/opt/spark/conf
      - ./spark/work:/opt/spark/work
      - ./work/data:/data

  python:
    image: jupyter/pyspark-notebook:python-3.8
    container_name: python
    hostname: python
    ports:
      - 8888:8888
      - 4040:4040
    volumes:
      - ./work:/home/jovyan/work
      - ./work/data:/data
